apiVersion: v1
kind: Service

metadata:
  name: {{ include "goal-setter-app.fullname" . }}-mongo

spec:
  clusterIP: None
  publishNotReadyAddresses: true

  selector:
    app: mongo

  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
      protocol: TCP