apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: {{ include "goal-setter-app.fullname" . }}-backend-secret

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore

  target:
    name: {{ include "goal-setter-app.fullname" . }}-backend-secret
    creationPolicy: Owner

    template:
      engineVersion: v2

      data:
        JWT_SECRET: "{{ `{{ .jwtSecret }}` }}"

        REFRESH_TOKEN_SECRET: "{{ `{{ .refreshTokenSecret }}` }}"

        MONGO_URI: >-
          mongodb://{{ `{{ .mongoUsername }}` }}:{{ `{{ .mongoPassword }}` }}@{{ include "goal-setter-app.fullname" . }}-mongo-0.{{ include "goal-setter-app.fullname" . }}-mongo:27017,{{ include "goal-setter-app.fullname" . }}-mongo-1.{{ include "goal-setter-app.fullname" . }}-mongo:27017,{{ include "goal-setter-app.fullname" . }}-mongo-2.{{ include "goal-setter-app.fullname" . }}-mongo:27017/?replicaSet={{ .Values.mongodb.replicaSet }}&authSource=admin

  data:
    - secretKey: jwtSecret
      remoteRef:
        key: goal-setter/backend-secrets
        property: JWT_SECRET

    - secretKey: refreshTokenSecret
      remoteRef:
        key: goal-setter/backend-secrets
        property: REFRESH_TOKEN_SECRET

    - secretKey: mongoUsername
      remoteRef:
        key: goal-setter/mongodb-credentials
        property: username

    - secretKey: mongoPassword
      remoteRef:
        key: goal-setter/mongodb-credentials
        property: password