apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: {{ include "goal-setter-app.fullname" . }}-mongo-credentials

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore

  target:
    name: {{ include "goal-setter-app.fullname" . }}-mongo-credentials
    creationPolicy: Owner

  data:
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: goal-setter/mongodb-credentials
        property: username

    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: goal-setter/mongodb-credentials
        property: password